language: swift
osx_image: xcode12.2
script:
  - xcodebuild clean test -project MarvelUI.xcodeproj -scheme MarvelUI -destination "platform=iOS Simulator,OS=14.2,name=iPhone 12 Pro" -configuration Debug -enableCodeCoverage YES
after_success:
  - bash <(curl -s https://codecov.io/bash)